---

# Here we define rules about our issue and merge requests triange.
# See https://gitlab.com/gitlab-org/gitlab-triage

resource_rules:
  branches:
    rules:

      # Delete old branches:

      - name: Delete stale branches
        conditions:
          date:
            attribute: committed_date
            condition: older_than
            interval_type: months
            interval: 1
        actions:
          delete: true

  issues:
    rules:

      # Stale issues:

      - name: Comment stale issues
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: days
            interval: 80
          forbidden_labels:
            - "validation:stale"
          state: opened
        actions:
          labels:
            - "validation:stale"
          comment: |
            This issue has been open for too long (since {{updated_at}}).
            And is still not resolved. Maybe no one needs it?
            It would be closed in 10 days automatically.

            In case you really need this issue,
            tell me so by writing "This is still on scope".
            And remove ~"validation:stale" label.

            In case it is ok to be closed, just do not touch it.
            And it will be automatically closed. Or close it right way.

            Thanks!

            CC {{author}} {{assignees}}
      - name: Close stale issues
        conditions:
          date:
            attribute: updated_at
            condition: older_than
            interval_type: days
            interval: 10
          labels:
            - "validation:stale"
          state: opened
        actions:
          status: close
          remove_labels:
            - "validation:stale"
          comment: |
            Closed as stale. Create a new issue in case you will need this.
            /unassign
            /remove_milestone
            /remove_estimate
            /remove_due_date
            /clear_weight
            /lock

      # Issue labels:

      - name: Validate that all issues have at least one label with type
        conditions:
          forbidden_labels:
            - "validation:labels"
          ruby: |
            !resource["labels"].any? { |label| label.start_with?("type::") }
        actions:
          labels:
            - "validation:labels"
          comment: |
            This issue does not have an issue type.
            Please, clarify it. CC {{author}}

            Steps to clarify it.
            1. Add proper `type::` label to this issue
            2. Make sure that you use an [issue template](/.gitlab/issue_templates) in the future
            3. Label ~"validation::labels" will be removed automatically
      - name: Remove validation label when at least one label exist
        conditions:
          labels:
            - "validation:labels"
          ruby: |
            resource["labels"].any? { |label| label.start_with?("type::") }
        actions:
          remove_labels:
            - "validation:labels"

      # Invalid issues:

      - name: Validate that all issues have description
        conditions:
          state: opened
          ruby: |
            not resource["description"] or resource["description"] == ""
        actions:
          labels:
            - "validation:invalid"
          comment: |
            This issue is invalid, since it does not have any description.
            Open a new one.

      # Estimates:

      - name: Label issues without an estimate
        conditions:
          ruby: |
            resource["time_stats"]["time_estimate"] == 0
          forbidden_labels:
            - "validation:estimate"
          state: opened
        actions:
          labels:
            - "validation:estimate"
          comment: |
            This issue is not estimated.
            {{author}}, ping your architect to do it.
            Then label ~"validation:estimate"
            will be removed automatically for you.
      - name: Unlabel issues with an estimate
        conditions:
          ruby: |
            resource["time_stats"]["time_estimate"] != 0
          labels:
            - "validation:estimate"
          state: opened
        actions:
          remove_labels:
            - "validation:estimate"

      # Deadlines:

      - name: Mildly comment deadlines
        conditions:
          ruby: |
            resource["due_date"] and DateTime.now + 7 >= resource["due_date"]
          forbidden_labels:
            - "deadline::soft"
            - "deadline::hard"
            - "deadline::miss"
          state: opened
        actions:
          labels:
            - "deadline::soft"
          comment: |
            The issue's deadline is coming. Better resolve it.
            CC {{author}} {{assignees}}
      - name: Strongly comment deadlines
        conditions:
          ruby: |
            resource["due_date"] and DateTime.now + 3 >= resource["due_date"]
          forbidden_labels:
            - "deadline::hard"
            - "deadline::miss"
          state: opened
        actions:
          labels:
            - "deadline::hard"
          remove_labels:
            - "deadline::soft"
          comment: |
            This issue is now on fire! :fire: Quick actions are required.
            Global ping for all! {{author}} {{assignees}}
      - name: Sadly comment missed deadlines
        conditions:
          ruby: |
            resource["due_date"] and DateTime.now >= resource["due_date"]
          forbidden_labels:
            - "deadline::miss"
          state: opened
        actions:
          labels:
            - "deadline::miss"
          remove_labels:
            - "deadline::hard"
            - "deadline::soft"
          comment: |
            The deadline was missed.
            This incident will be reported to the stakeholders.
            Status of this task needs to be discussed further.
            Most likely, it still makes sense to finish it,
            but it might be already useless.

      # Invalid issues:

      - name: Close invalid issues
        conditions:
          state: opened
          labels:
            - validation:invalid
        actions:
          status: close
          comment: |
            Hey, looks like your issue is invalid.

            Please, make sure that your know
            [how to work with issues](https://wemake-services.github.io/meta/rsdp/creating-issues/).

            Create a new one if you have something to report / suggest.

            In case you have any questions, please ask them in a new issue.
            Label it as ~"documentation" and assign your architect.
            /unassign
            /remove_milestone
            /remove_estimate
            /remove_due_date
            /clear_weight
            /lock

  merge_requests:
    rules:

      # Copy metadata from issues to merge requests:

      - name: Copy metadata from the original issue
        conditions:
          state: opened
          forbidden_labels:
            - "mr::processed"
          ruby: |
            closes_issues.size > 0
        actions:
          labels:
            - "mr::processed"
          comment: |
            /copy_metadata ##{closes_issues[0].resource["iid"]}

      # Comment on merge requests without time tracking:

      - name: Label merge requests without a spent time
        conditions:
          ruby: |
            resource["time_stats"]["total_time_spent"] == 0
          forbidden_labels:
            - "validation:estimate"
          state: opened
        actions:
          labels:
            - "validation:estimate"
          comment: |
            This merge request does not have spent time.
            {{author}}, use `/spend` [command](https://docs.gitlab.com/user/project/quick_actions).
            Then label ~"validation:estimate"
            will be removed automatically for you.

      - name: Unlabel merge requests with time spent
        conditions:
          ruby: |
            resource["time_stats"]["total_time_spent"] != 0
          labels:
            - "validation:estimate"
          state: opened
        actions:
          remove_labels:
            - "validation:estimate"

      # Long merge requests and code reviews:

      - name: Comment stale merge requests
        conditions:
          ruby: |
            DateTime.now >= DateTime.parse(
              resource["updated_at"]
            ) + (3.0 / 24) and not resource["work_in_progress"]
          state: opened
          forbidden_labels:
            - "validation:stale"
        actions:
          labels:
            - "validation:stale"
          comment: |
            Looks like this merge request is stale.
            It was last updated at {{updated_at}}

            Why no one is working on it?

            How can this be resolved?
            1. {{author}}, mark it a WIP if it has "Work in Progress" state.
               Use `/wip` command to do that.
               Then remove ~"validation:stale" label
            2. Ping the reviewer to submit a review,
               if there's one and it is a right time for that {{assignee}}
            3. In case you cannot receive a single review
               for more than two hours, ping your architect
            4. Merge it if possible. Make sure to rebase it.
               Or assign our merge bot (@kira\-bot) to rebase / merge it for you
            5. Apply ~"validation:invalid" label in case it was created by a mistake

      # Invalid merge requests:

      - name: Close invalid merge requests
        conditions:
          state: opened
          labels:
            - validation:invalid
        actions:
          status: close
          comment: |
            Hey, looks like your merge request is invalid.

            Please, make sure that your know
            [how to work with merge requests](https://wemake-services.github.io/meta/rsdp/creating-merge-requests/).

            Create a new one if you have something to submit.

            In case you have any questions, please ask them in a new issue.
            Label it as ~"documentation" and assign your architect.
            /unassign
            /remove_milestone
            /lock
