name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: build docker image
      run: docker build . --tag=wemakeservices/kira-stale

    - name: run minimal docker-based test
      run: |
        docker run \
          wemakeservices/kira-stale \
          gitlab-triage --help

  deploy:
    if: "github.event_name == 'push' && github.repository == 'wemake-services/kira-stale'"
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: wemakeservices/kira-stale
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
